// <auto-generated />
using System;
using EFcore_test.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFcore_test.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("EFcore_test.Models.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kursy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "MD"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "ZSI"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "SSI"
                        });
                });

            modelBuilder.Entity("EFcore_test.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdStudenta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdStudenta")
                        .IsUnique();

                    b.ToTable("Studenci");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdStudenta = 1
                        },
                        new
                        {
                            Id = 2,
                            IdStudenta = 2
                        },
                        new
                        {
                            Id = 3,
                            IdStudenta = 3
                        },
                        new
                        {
                            Id = 4,
                            IdStudenta = 4
                        },
                        new
                        {
                            Id = 5,
                            IdStudenta = 5
                        },
                        new
                        {
                            Id = 6,
                            IdStudenta = 6
                        },
                        new
                        {
                            Id = 7,
                            IdStudenta = 7
                        },
                        new
                        {
                            Id = 8,
                            IdStudenta = 8
                        },
                        new
                        {
                            Id = 9,
                            IdStudenta = 9
                        },
                        new
                        {
                            Id = 10,
                            IdStudenta = 10
                        },
                        new
                        {
                            Id = 11,
                            IdStudenta = 11
                        },
                        new
                        {
                            Id = 12,
                            IdStudenta = 12
                        },
                        new
                        {
                            Id = 13,
                            IdStudenta = 13
                        },
                        new
                        {
                            Id = 14,
                            IdStudenta = 14
                        },
                        new
                        {
                            Id = 15,
                            IdStudenta = 15
                        },
                        new
                        {
                            Id = 16,
                            IdStudenta = 16
                        });
                });

            modelBuilder.Entity("EFcore_test.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RokStudiow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Profile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataUrodzenia = new DateTime(2000, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Jan",
                            Nazwisko = "Kowalski",
                            RokStudiow = 2,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            DataUrodzenia = new DateTime(2001, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Anna",
                            Nazwisko = "Nowak",
                            RokStudiow = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            DataUrodzenia = new DateTime(1999, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Piotr",
                            Nazwisko = "Zieliński",
                            RokStudiow = 3,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            DataUrodzenia = new DateTime(2000, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Maria",
                            Nazwisko = "Wiśniewska",
                            RokStudiow = 2,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            DataUrodzenia = new DateTime(1998, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Tomasz",
                            Nazwisko = "Lewandowski",
                            RokStudiow = 4,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 6,
                            DataUrodzenia = new DateTime(2002, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Katarzyna",
                            Nazwisko = "Wójcik",
                            RokStudiow = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 7,
                            DataUrodzenia = new DateTime(2000, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Michał",
                            Nazwisko = "Kowalczyk",
                            RokStudiow = 2,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 8,
                            DataUrodzenia = new DateTime(1999, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Magdalena",
                            Nazwisko = "Jankowska",
                            RokStudiow = 3,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 9,
                            DataUrodzenia = new DateTime(2001, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Łukasz",
                            Nazwisko = "Mazur",
                            RokStudiow = 1,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 10,
                            DataUrodzenia = new DateTime(1998, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Agnieszka",
                            Nazwisko = "Krawczyk",
                            RokStudiow = 5,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 11,
                            DataUrodzenia = new DateTime(2000, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Paweł",
                            Nazwisko = "Szymański",
                            RokStudiow = 2,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 12,
                            DataUrodzenia = new DateTime(2002, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Joanna",
                            Nazwisko = "Dąbrowska",
                            RokStudiow = 1,
                            StudentId = 12
                        },
                        new
                        {
                            Id = 13,
                            DataUrodzenia = new DateTime(1999, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Marcin",
                            Nazwisko = "Zając",
                            RokStudiow = 3,
                            StudentId = 13
                        },
                        new
                        {
                            Id = 14,
                            DataUrodzenia = new DateTime(2001, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Natalia",
                            Nazwisko = "Kozłowska",
                            RokStudiow = 2,
                            StudentId = 14
                        },
                        new
                        {
                            Id = 15,
                            DataUrodzenia = new DateTime(1998, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Adam",
                            Nazwisko = "Jankowski",
                            RokStudiow = 4,
                            StudentId = 15
                        },
                        new
                        {
                            Id = 16,
                            DataUrodzenia = new DateTime(2000, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Imie = "Aleksandra",
                            Nazwisko = "Wojciechowska",
                            RokStudiow = 2,
                            StudentId = 16
                        });
                });

            modelBuilder.Entity("KursStudent", b =>
                {
                    b.Property<int>("KursyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudenciId")
                        .HasColumnType("INTEGER");

                    b.HasKey("KursyId", "StudenciId");

                    b.HasIndex("StudenciId");

                    b.ToTable("KursStudent");
                });

            modelBuilder.Entity("EFcore_test.Models.StudentProfile", b =>
                {
                    b.HasOne("EFcore_test.Models.Student", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("EFcore_test.Models.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("KursStudent", b =>
                {
                    b.HasOne("EFcore_test.Models.Kurs", null)
                        .WithMany()
                        .HasForeignKey("KursyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFcore_test.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFcore_test.Models.Student", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
